### ISSUE TITLE
Slow input response on startup with more than one open tab

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#1590]
Originally reported on Google Code with ID 1590

```
OS version: Win7 x64
ConEmu version: 140523

When I start Conemu with at least two startup tabs (both git bash, i.e. C:\Program
Files (x86)\Git\bin\sh.exe), in all but the last tab, all input response is noticably
delayed, i.e. I type and it is only displayed after a second or so. The output is also
a little delayed. The problem goes away after I restart the tab. It only happnes when
more than tab opens at startup. 

Example task commands:

""C:\Program Files (x86)\Git\bin\sh.exe" --login -i"  -cur_console:d:C:\Users\user.folder\folder"-cur_console:t:title"

""C:\Program Files (x86)\Git\bin\sh.exe" --login -i"  -cur_console:d:C:\Users\user.folder\folder"-cur_console:t:title"

Please let me know if I can provide more information. Thanks!
```

Reported by `mjstaffa` on 2014-05-26 08:42:39

**Comment by Elfy** [comment]
I have the same issue with 151224 [64]. I use auto save/restore and on restore there are usually several slow tabs.

Some observations: 

1) Content of <Startup> key is inconsistent. For example a command may start with &gt; and have -new_console:b in it. Also all commands are prefixed with *, even though original tasks were not marked this way. I even saw cases where there were more commands stored than "Count" value specified.

2) Editing commands in <Startup> key so that no command has -cur_console:b and no * prefix makes things interesting: with exact same ConEmu.xml the issue appears only about half of the time.

3) StartCreateDelay=1000 solves the issue. For edited ConEmu.xml lower value is sufficient (about 600)

Clearly there is some race somewhere.

I did not find any obvious dependence on what exactly was running in tabs.

**Comment by Maximus5** [comment]
I can't find any problems within ConEmu itself and suppose at the moment, that race exists in conhost code.

Also. This tracker is read only.

**Comment by quantbo** [comment]
I have the same problem. Running on Win 7, 64 bit.  Typing in the terminal window it can take significant time for the characters to display.

**Comment by Maximus5** [comment]
* https://github.com/Maximus5/ConEmu/issues/297
* http://conemu.github.io/en/SettingsStartup.html

Anyway, this tracker is deprecated.
