### ISSUE TITLE
7zip not found! It is not installed?

### ISSUE THREAD

**Issue by Maximus5** [Maximus5/conemu-old-issues#939]
Originally reported on Google Code with ID 939

```
Required information!
OS version: Win7 SP0 x64
ConEmu version: 130210

*Bug description*
7zip not found! It is not installed?
Goto 'Update' page and check 7-zip command


*Steps to reproduction*
1. put 7za.exe anywhere in %PATH%
2. set `7za.exe x -y "%1"` at Main\Update settings
3. Check for update.

Any ideas? This bug was introduced at r130205 (Checking 7zip/WinRar existence before
updating with 7z package.) and it blocks of auto update.
```

Reported by `ehysta` on 2013-02-13 09:34:05

**Comment by wakywayne** [comment]
Hey how did you end up fixing this issue I seem to have the same problem

**Comment by rocket-matt** [comment]
Yes, I have the same issue despite 7zip being in my path and working correctly when I have my command prompt.  I installed both 7zip and cmder using Scoop.

**Comment by rocket-matt** [comment]
OK, I solved my issue by going into the update page in settings and setting the correct path.  I replaced the path with `%USERPROFILE%\scoop\shims\7zg.exe ...`.  Before it pointed to `Program Files`.  But the update process still failed since it couldn't find the 7z file it tried to open.  Maybe it is just broken if you use scoop to install `cmder`.

**Comment by rocket-matt** [comment]
My mistake about the update process failing.  I missed a start quote on the file path for 7zg.exe.  It was enough to pass the check that 7zg exists but also enough to fail the update batch file that extracts the update from the 7z file.  Now `cmder` updates correctly under scoop.

If there is one fix to do, perhaps it's to support running 7zg via the PATH variable.  Removing the folder of 7zg.exe in the update settings does not work as it requires an exact path, even though the batch file that does the updating doesn't require it because presumably it would use the PATH variable fine.
